name: MoreEnchant
version: 1.1
main: com.herzchen.moreenchant.MoreEnchant
api-version: 1.20
description: New enchantments for minecraft
softdepend: [WorldGuard]
author: Herzchen

commands:
  moe:
    description: MoreEnchant commands
    usage: /moe <enchant|disenchant|reload|help> [enchantment] [level]

permissions:
  moreenchant.*:
    description: Gives access to all MoreEnchant commands
    default: op
    children:
      moreenchant.enchant: true
      moreenchant.disenchant: true
      moreenchant.reload: true
  moreenchant.enchant:
    description: Allows using enchant command
    default: op
  moreenchant.disenchant:
    description: Allows using disenchant command
    default: op
  moreenchant.reload:
    description: Allows reloading the config
    default: op